apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: epvciwj3q-python 
  janus-idp.io/tekton: epvciwj3q-python
  backstage.io/kubernetes-id: epvciwj3q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: epvciwj3q-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml