apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: epvciwj3q-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:7a474ac877f0cb1f4207fe9ec56b1bab6a0bccff@sha256:f368d9bdaf33d9dcd75bf50430e123f1067f50ebc9252ccf4a18e6a93c183197
          name: container-image
